version: '3.7'
services:
# Traefik
  traefik:
    image: traefik:v2.7.0
    container_name: traefik
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/etc/traefik/traefik.yml:ro
      - ./config/:/etc/traefik/custom/:ro
      - ./letsencrypt:/letsencrypt
      - ./log:/var/log:rw
    networks:
      - traefik
    restart: unless-stopped

  # Deluge : P2P Dl Online
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
    volumes:
      - ${PWD}/deluge/:/config
      - ${PWD}/deluge/downloads/:/downloads
    restart: unless-stopped
    
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/tv
      - /path/to/movies:/movies
    restart: unless-stopped
    networks:
      - traefik
    
## NETWORKS
networks:
  traefik:
    name: traefik
    external: false
